### PR TITLE
Fix hlint

### PR DESCRIPTION
**Pull request by JekaGrib**
Remove redudant do  at   ./test/Spec/Vk/App.hs:33:13:  (Warning)

#1

### CODE REVIEW

**Comment by ghost** [comment]
Мне хлинт по прежнему выдает ошибки:

src/Tg/App.hs:(530,3)-(532,22): Suggestion: Replace case with maybe
Found:
  case textMsg msg of
    Just txt -> checkTextButton txt
    Nothing -> Nothing
Perhaps:
  maybe Nothing checkTextButton (textMsg msg)

src/Tg/Conf.hs:(72,3)-(74,22): Suggestion: Replace case with maybe
Found:
  case str of
    Nothing -> inputBotToken
    Just n -> return n
Perhaps:
  maybe inputBotToken return str

src/Tg/MainTg.hs:23:39-53: Warning: Use empty
Found:
  Map.fromList []
Perhaps:
  Data.Map.empty

src/Vk/AppT.hs:28:23-45: Suggestion: Use first
Found:
  \ (s1, s2) -> (f s1, s2)
Perhaps:
  Data.Bifunctor.first f
Note: increases laziness

src/Vk/AppT.hs:29:23-45: Suggestion: Use second
Found:
  \ (s1, s2) -> (s1, f s2)
Perhaps:
  Data.Bifunctor.second f
Note: increases laziness

src/Vk/MainVk.hs:23:15-29: Warning: Use empty
Found:
  Map.fromList []
Perhaps:
  Data.Map.empty

test/Spec/Tg/App.hs:20:14-28: Warning: Use empty
Found:
  Map.fromList []
Perhaps:
  Map.empty

test/Spec/Vk/App.hs:22:14-28: Warning: Use empty
Found:
  Map.fromList []
Perhaps:
  Map.empty

**Comment by JekaGrib** [comment]
I have "no hints". Fix yours? Is it because of the hlint settings?

**Comment by ghost** [comment]
Может из-за версии хлинта. Да, поправь эти, пожалуйста

**Comment by ghost** [comment]
Вот ещё последнее выдеает:
```
src/Tg/App.hs:529:19-61: Suggestion: Use =<<
Found:
  maybe Nothing checkTextButton (textMsg msg)
Perhaps:
  checkTextButton =<< textMsg msg
```
поправь это тоже, пожалуйста

**Comment by ghost** [comment]
Все хорошо

**Pull request merged**
